version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb+srv://deepukumar8991:ztlqS2vR65HukYMf@fastifytestapp.hjf4n.mongodb.net/?retryWrites=true&w=majority&appName=FastifyTestApp
      - JWT_SECRET=ztlqS2vR65HukYMf
    restart: always
    networks:
      - mynetwork

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  mynetwork:
